### ISSUE TITLE
ha cards in HACustomCard.vue

### ISSUE THREAD

**Issue by ddeguglielmo** [iva-stolnik/vue-ha-lovelace-connector#1]
Hello,
thanks for sharing your code. 

I have just tried the example and it works perfectly :)

Have you ever tried to use home assistant native cards (such as the entity or light card) in the HACustomCard.vue component?
My goal is to create the list of lights of my house in the HACustomCard.vue component.

Thanks.

**Comment by iva-stolnik** [comment]
Hello,

thank you for your feedback. I haven't tried to use native elements since I'm building my own fully custom dashboard with vue and pinia. 

My current approach is to pass hass object from lit-custom-card.js to vue component via dispatchEvent. This way I have access to every service, state, or any other HA property/method including api and socket. After hass object is passed to vue component I am subscribing to state_changed event via socket to keep pinia state updated. It gives me full control over actions and state which I don't really have with native cards.

I also use hass-more-info event for entities, but while it works very nice for some action calls it isn't very good for quick dashboard lookup.

```
// Dispatching 'hass-more-info' event
const event= new Event('hass-more-info', {
    bubbles: true,
    composed: true,
});

event.detail = { entityId: 'light.office' };
window.document.querySelector('home-assistant').dispatchEvent(event);
```


EDIT: I have found one quick solution and pushed it to dev branch, Its not perfect and I haven't really tested it but with some improvements/additions it will do exactly what you need.

**Comment by ddeguglielmo** [comment]
Hello,
thank you so much for your prompt answer. 

I will try the example in the dev branch ASAP.

Thanks again.

**Comment by iva-stolnik** [comment]
You're very welcome! I have just updated the 'dev' branch with some improvements and optimizations, and I'm actually pretty satisfied with how it works now. Hopefully, this will do exactly what you're looking for. Happy automating and customizing :)
